config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :providers
  devise_for :users
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/provider.rb
class Provider < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  # layout Proc.new { |controller| controller.devise_controller? ? 'layouts/login' : 'layouts/application' }

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /providers
  def index
    @providers = Provider.all
  end

  # GET /providers/1
  def show
  end

  # GET /providers/new
  def new
    @provider = Provider.new
  end

  # GET /providers/1/edit
  def edit
  end

  # POST /providers
  def create
    @provider = Provider.new(provider_params)

    if @provider.save
      redirect_to @provider, notice: 'Provider was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /providers/1
  def update
    if @provider.update(provider_params)
      redirect_to @provider, notice: 'Provider was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /providers/1
  def destroy
    @provider.destroy
    redirect_to providers_url, notice: 'Provider was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider = Provider.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def provider_params
      params.require(:provider).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.slim
.content-wrapper
  section.content-header
    h1
      | Blank page
      small Examples
    ol.breadcrumb
      li
        a href="#"
          i.fa.fa-file
          | Home
      li
        a href="#"  Examples
      li.active Blank page

app/views/layouts/admin/_footer.html.slim
footer.main-footer
  .pull-right.hidden-xs
    b Version
    | 1.0.0.0
  strong
    | Copyright &copy; 2017
    a href="http://f9solucoes.com.br"  F9soluções

app/views/layouts/admin/_sidebar.html.slim
aside.main-sidebar
  /! sidebar: style can be found in sidebar.less
  section.sidebar
    /! Sidebar user panel
    .user-panel
      .pull-left.image
        img.img-circle alt=("User Image") src="../../templates/AdminLTE/dist/img/avatar04.png" /
      .pull-left.info
        p Desenvolvimento
        a href="#"
          i.fa.fa-circle.text-success
          | Online
    /! search form
    form.sidebar-form action="#" method="get"
      .input-group
        input.form-control name="q" placeholder="Search..." type="text" /
        span.input-group-btn
          button#search-btn.btn.btn-flat name="search" type="submit"
            i.fa.fa-search
    /! /.search form
    /! sidebar menu: : style can be found in sidebar.less
    ul.sidebar-menu
      li.header MENU

      li
        a href="/companies"
          i.fa.fa-institution
          span Empresas
      li
        a href="/providers"
          i.fa.fa-truck
          span Fornecedores
      li
        a href="/equipaments"
          i.fa.fa-wrench
          span Equipamentos
      li
        a href="#"
          i.fa.fa-user-plus
          span Usuários

      li.treeview
        a href="#"
          i.fa.fa-barcode
          span Moviments
          span.pull-right-container
            i.fa.fa-angle-left.pull-right
        ul.treeview-menu
          li
            a href="#"
              i.fa.fa-circle-o
              | Entrada
          li
            a href="#"
              i.fa.fa-circle-o
              | Saída
      li
        a href="/diagrams"
          i.fa.fa-database
          span DER




      / li.header LABELS
      / li
      /   a href="#"
      /     i.fa.fa-circle-o.text-red
      /     span Important
      / li
      /   a href="#"
      /     i.fa.fa-circle-o.text-yellow
      /     span Warning
      / li
      /   a href="#"
      /     i.fa.fa-circle-o.text-aqua
      /     span Information
  /! /.sidebar

app/views/layouts/admin/_top.html.slim
nav.navbar.navbar-static-top
  a.sidebar-toggle data-toggle="offcanvas" href="#" role="button"
    span.sr-only Toggle navigation
    span.icon-bar
    span.icon-bar
    span.icon-bar
  .navbar-custom-menu
    ul.nav.navbar-nav



      li.dropdown.user.user-menu
        a.dropdown-toggle data-toggle="dropdown" href="#"
          img.user-image alt=("User Image") src="../../templates/AdminLTE/dist/img/avatar04.png" /
          span.hidden-xs Alexander Pierce
        ul.dropdown-menu
          li.user-header
            img.img-circle alt=("User Image") src="../../templates/AdminLTE/dist/img/avatar04.png" /
            p
              | Alexander Pierce - Web Developer
              small Member since Nov. 2012
          li.user-body
            .row
              .col-xs-4.text-center
                a href="#"  Followers
              .col-xs-4.text-center
                a href="#"  Sales
              .col-xs-4.text-center
                a href="#"  Friends
          li.user-footer
            .pull-left
              a.btn.btn-default.btn-flat href="#"  Profile
            .pull-right
              a.btn.btn-default.btn-flat href="#"  Sign out

app/views/layouts/application-bkp.html.slim
doctype html
html
  head
    = csrf_meta_tags
    = favicon_link_tag 'computer.ico'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    title IventoryControll
    meta charset="utf-8" /
    meta content="IE=edge" http-equiv="X-UA-Compatible" /
    meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport" /
    link href="../../templates/AdminLTE/bootstrap/css/bootstrap.min.css" rel="stylesheet" /
    link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet" /
    link href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" /
    link href="../../templates/AdminLTE/dist/css/AdminLTE.min.css" rel="stylesheet" /
    link href="../../templates/AdminLTE/dist/css/skins/_all-skins.min.css" rel="stylesheet" /

    /! HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
    /! WARNING: Respond.js doesn't work if you view the page via file://
    /![if lt IE 9]
      | <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script
      | <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script
  body.hold-transition.skin-blue.sidebar-mini
    .wrapper
      header.main-header
        a.logo href="../../templates/AdminLTE/index2.html"
          span.logo-mini
            b> I
            | Ctrl
          span.logo-lg
            b> Iventory
            | Controll

        = render 'layouts/admin/top'

      = render 'layouts/admin/sidebar'

      = yield

      = render 'layouts/admin/footer'

      / aside.control-sidebar.control-sidebar-dark
      /   ul.nav.nav-tabs.nav-justified.control-sidebar-tabs
      /     li
      /       a data-toggle="tab" href="#control-sidebar-home-tab"
      /         i.fa.fa-home
      /     li
      /       a data-toggle="tab" href="#control-sidebar-settings-tab"
      /         i.fa.fa-gears
      /   .tab-content
      /     #control-sidebar-home-tab.tab-pane
      /       h3.control-sidebar-heading Recent Activity
      /       ul.control-sidebar-menu
      /         li
      /           a href="javascript:void(0)"
      /             i.menu-icon.fa.fa-birthday-cake.bg-red
      /           .menu-info
      /             h4.control-sidebar-subheading Langdon's Birthday
      /             p Will be 23 on April 24th
      /         li
      /           a href="javascript:void(0)"
      /             i.menu-icon.fa.fa-user.bg-yellow
      /           .menu-info
      /             h4.control-sidebar-subheading Frodo Updated His Profile
      /             p New phone +1(800)555-1234
      /         li
      /           a href="javascript:void(0)"
      /             i.menu-icon.fa.fa-envelope-o.bg-light-blue
      /           .menu-info
      /             h4.control-sidebar-subheading Nora Joined Mailing List
      /             p nora@example.com
      /         li
      /           a href="javascript:void(0)"
      /             i.menu-icon.fa.fa-file-code-o.bg-green
      /           .menu-info
      /             h4.control-sidebar-subheading Cron Job 254 Executed
      /             p Execution time 5 seconds
      /       /! /.control-sidebar-menu
      /       h3.control-sidebar-heading Tasks Progress
      /       ul.control-sidebar-menu
      /         li
      /           a href="javascript:void(0)"
      /           h4.control-sidebar-subheading
      /             | Custom Template Design
      /             span.label.label-danger.pull-right 70%
      /           .progress.progress-xxs
      /             .progress-bar.progress-bar-danger style=("width: 70%")
      /         li
      /           a href="javascript:void(0)"
      /           h4.control-sidebar-subheading
      /             | Update Resume
      /             span.label.label-success.pull-right 95%
      /           .progress.progress-xxs
      /             .progress-bar.progress-bar-success style=("width: 95%")
      /         li
      /           a href="javascript:void(0)"
      /           h4.control-sidebar-subheading
      /             | Laravel Integration
      /             span.label.label-warning.pull-right 50%
      /           .progress.progress-xxs
      /             .progress-bar.progress-bar-warning style=("width: 50%")
      /         li
      /           a href="javascript:void(0)"
      /           h4.control-sidebar-subheading
      /             | Back End Framework
      /             span.label.label-primary.pull-right 68%
      /           .progress.progress-xxs
      /             .progress-bar.progress-bar-primary style=("width: 68%")
      /     #control-sidebar-stats-tab.tab-pane Stats Tab Content
      /     #control-sidebar-settings-tab.tab-pane
      /       form method="post"
      /         h3.control-sidebar-heading General Settings
      /         .form-group
      /           label.control-sidebar-subheading
      /             | Report panel usage
      /             input.pull-right checked="" type="checkbox" /
      /           p
      /             | Some information about this general settings option
      /         .form-group
      /           label.control-sidebar-subheading
      /             | Allow mail redirect
      /             input.pull-right checked="" type="checkbox" /
      /           p
      /             | Other sets of options are available
      /         .form-group
      /           label.control-sidebar-subheading
      /             | Expose author name in posts
      /             input.pull-right checked="" type="checkbox" /
      /           p
      /             | Allow the user to show his name in blog posts
      /         h3.control-sidebar-heading Chat Settings
      /         .form-group
      /           label.control-sidebar-subheading
      /             | Show me as online
      /             input.pull-right checked="" type="checkbox" /
      /         .form-group
      /           label.control-sidebar-subheading
      /             | Turn off notifications
      /             input.pull-right type="checkbox" /
      /         .form-group
      /           label.control-sidebar-subheading
      /             | Delete chat history
      /             a.text-red.pull-right href="javascript:void(0)"
      /               i.fa.fa-trash-o
      / .control-sidebar-bg
    / script src="../../templates/AdminLTE/plugins/jQuery/jquery-2.2.3.min.js"
    script src="../../templates/AdminLTE/bootstrap/js/bootstrap.min.js"
    script src="../../templates/AdminLTE/plugins/slimScroll/jquery.slimscroll.min.js"
    script src="../../templates/AdminLTE/plugins/fastclick/fastclick.js"
    script src="../../templates/AdminLTE/dist/js/app.min.js"
    script src="../../templates/AdminLTE/dist/js/demo.js"

    = javascript_include_tag 'admin/jquery-2.2.3.min.js', 'data-turbolinks-track': 'reload'

app/views/layouts/application.html.slim
doctype html
html
  head
    = csrf_meta_tags
    = favicon_link_tag 'computer.ico'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    title IventoryControll
    meta charset="utf-8" /
    meta content="IE=edge" http-equiv="X-UA-Compatible" /
    meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport" /
    link href="../../templates/AdminLTE/bootstrap/css/bootstrap.min.css" rel="stylesheet" /
    link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet" /
    link href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" /
    link href="../../templates/AdminLTE/dist/css/AdminLTE.min.css" rel="stylesheet" /
    link href="../../templates/AdminLTE/dist/css/skins/_all-skins.min.css" rel="stylesheet" /

    /! HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
    /! WARNING: Respond.js doesn't work if you view the page via file://
    /![if lt IE 9]
      | <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script
      | <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script
  body.hold-transition.skin-blue.sidebar-mini
    .wrapper
      header.main-header
        a.logo href="../../templates/AdminLTE/index2.html"
          span.logo-mini
            b> I
            | Ctrl
          span.logo-lg
            b> Iventory
            | Controll

      /   = render 'layouts/admin/top'

      / = render 'layouts/admin/sidebar'
      = link_to 'sair', destroy_user_session_path, method: :delete, class: 'btn-danger'
      = yield

      = render 'layouts/admin/footer'

      / aside.control-sidebar.control-sidebar-dark
      /   ul.nav.nav-tabs.nav-justified.control-sidebar-tabs
      /     li
      /       a data-toggle="tab" href="#control-sidebar-home-tab"
      /         i.fa.fa-home
      /     li
      /       a data-toggle="tab" href="#control-sidebar-settings-tab"
      /         i.fa.fa-gears
      /   .tab-content
      /     #control-sidebar-home-tab.tab-pane
      /       h3.control-sidebar-heading Recent Activity
      /       ul.control-sidebar-menu
      /         li
      /           a href="javascript:void(0)"
      /             i.menu-icon.fa.fa-birthday-cake.bg-red
      /           .menu-info
      /             h4.control-sidebar-subheading Langdon's Birthday
      /             p Will be 23 on April 24th
      /         li
      /           a href="javascript:void(0)"
      /             i.menu-icon.fa.fa-user.bg-yellow
      /           .menu-info
      /             h4.control-sidebar-subheading Frodo Updated His Profile
      /             p New phone +1(800)555-1234
      /         li
      /           a href="javascript:void(0)"
      /             i.menu-icon.fa.fa-envelope-o.bg-light-blue
      /           .menu-info
      /             h4.control-sidebar-subheading Nora Joined Mailing List
      /             p nora@example.com
      /         li
      /           a href="javascript:void(0)"
      /             i.menu-icon.fa.fa-file-code-o.bg-green
      /           .menu-info
      /             h4.control-sidebar-subheading Cron Job 254 Executed
      /             p Execution time 5 seconds
      /       /! /.control-sidebar-menu
      /       h3.control-sidebar-heading Tasks Progress
      /       ul.control-sidebar-menu
      /         li
      /           a href="javascript:void(0)"
      /           h4.control-sidebar-subheading
      /             | Custom Template Design
      /             span.label.label-danger.pull-right 70%
      /           .progress.progress-xxs
      /             .progress-bar.progress-bar-danger style=("width: 70%")
      /         li
      /           a href="javascript:void(0)"
      /           h4.control-sidebar-subheading
      /             | Update Resume
      /             span.label.label-success.pull-right 95%
      /           .progress.progress-xxs
      /             .progress-bar.progress-bar-success style=("width: 95%")
      /         li
      /           a href="javascript:void(0)"
      /           h4.control-sidebar-subheading
      /             | Laravel Integration
      /             span.label.label-warning.pull-right 50%
      /           .progress.progress-xxs
      /             .progress-bar.progress-bar-warning style=("width: 50%")
      /         li
      /           a href="javascript:void(0)"
      /           h4.control-sidebar-subheading
      /             | Back End Framework
      /             span.label.label-primary.pull-right 68%
      /           .progress.progress-xxs
      /             .progress-bar.progress-bar-primary style=("width: 68%")
      /     #control-sidebar-stats-tab.tab-pane Stats Tab Content
      /     #control-sidebar-settings-tab.tab-pane
      /       form method="post"
      /         h3.control-sidebar-heading General Settings
      /         .form-group
      /           label.control-sidebar-subheading
      /             | Report panel usage
      /             input.pull-right checked="" type="checkbox" /
      /           p
      /             | Some information about this general settings option
      /         .form-group
      /           label.control-sidebar-subheading
      /             | Allow mail redirect
      /             input.pull-right checked="" type="checkbox" /
      /           p
      /             | Other sets of options are available
      /         .form-group
      /           label.control-sidebar-subheading
      /             | Expose author name in posts
      /             input.pull-right checked="" type="checkbox" /
      /           p
      /             | Allow the user to show his name in blog posts
      /         h3.control-sidebar-heading Chat Settings
      /         .form-group
      /           label.control-sidebar-subheading
      /             | Show me as online
      /             input.pull-right checked="" type="checkbox" /
      /         .form-group
      /           label.control-sidebar-subheading
      /             | Turn off notifications
      /             input.pull-right type="checkbox" /
      /         .form-group
      /           label.control-sidebar-subheading
      /             | Delete chat history
      /             a.text-red.pull-right href="javascript:void(0)"
      /               i.fa.fa-trash-o
      / .control-sidebar-bg
    / script src="../../templates/AdminLTE/plugins/jQuery/jquery-2.2.3.min.js"
    script src="../../templates/AdminLTE/bootstrap/js/bootstrap.min.js"
    script src="../../templates/AdminLTE/plugins/slimScroll/jquery.slimscroll.min.js"
    script src="../../templates/AdminLTE/plugins/fastclick/fastclick.js"
    script src="../../templates/AdminLTE/dist/js/app.min.js"
    script src="../../templates/AdminLTE/dist/js/demo.js"

    = javascript_include_tag 'admin/jquery-2.2.3.min.js', 'data-turbolinks-track': 'reload'

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/providers/_form.html.slim
= simple_form_for(@provider) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/providers/edit.html.slim
h1 Editing provider

== render 'form'

=> link_to 'Show', @provider
'|
=< link_to 'Back', providers_path

app/views/providers/index.html.slim
h1 Listing providers

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @providers.each do |provider|
      tr
        td = provider.name
        td = link_to 'Show', provider
        td = link_to 'Edit', edit_provider_path(provider)
        td = link_to 'Destroy', provider, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Provider', new_provider_path

app/views/providers/new.html.slim
h1 New provider

== render 'form'

= link_to 'Back', providers_path

app/views/providers/show.html.slim
p#notice = notice

p
  strong Name:
  = @provider.name

=> link_to 'Edit', edit_provider_path(@provider)
'|
=< link_to 'Back', providers_path

app/views/users/_form.html.slim
= simple_form_for(@user) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :email
    = f.input :password
    = f.input :password_confirmation

  .form-actions
    = f.button :submit

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

=> link_to 'Show', @user
'|
=< link_to 'Back', users_path

app/views/users/index.html.slim
h1 Listing users

table
  thead
    tr
      th Name
      th Email
      th Password
      th Password confirmation
      th
      th
      th

  tbody
    - @users.each do |user|
      tr
        td = user.name
        td = user.email
        td = user.password
        td = user.password_confirmation
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice = notice

p
  strong Name:
  = @user.name
p
  strong Email:
  = @user.email
p
  strong Password:
  = @user.password
p
  strong Password confirmation:
  = @user.password_confirmation

=> link_to 'Edit', edit_user_path(@user)
'|
=< link_to 'Back', users_path